[package]
name = "wikimedia-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.1.8", features = ["derive", "env"] }
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["gzip"] }
scraper = "0.15.0"
tokio = { version = "1.26.0", features = ["macros", "net", "rt-multi-thread", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

[profile.release]
# strip = true
